# Gmail SMTP
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: prettier.homes.noreply@gmail.com
    password: sbdv kchz cldp pfru
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  account:
    activate:
      subject: Activation Email
      template: email-activate-template.ftl
      email-img: activate.png
      text: |
        <In this property, you can set the text of the email.>
    forgot:
      subject: Forgot Password
      template: forgot-password-mail.ftl
      email-img: https://i.imgur.com/P5FfKNl.png
      text: |
        <In this property, you can set the text of the email.>